Support TON Connect standard  CHA-42
TON-42/new_vite_frontend pull request #10
Opened 2024-06-14 13:57 UTC by lmangall

https://linear.app/chatpay/issue/CHA-233/support-ton-connect-standard

2024-06-14 15:13 UTC, 552020 commented
Branch has conflicts.

2024-06-14 15:14 UTC, 552020 requested changes
Conflicts

2024-06-14 17:01 UTC, lmangall commented
Solved

2024-06-14 19:17 UTC, 552020 requested changes
Good job, still some question and a minor change request.

2024-06-14 19:17 UTC, 552020 commented on manifest.json
> +	"description": "Earn money from your Telegram chats by bundling them into AI training datasets.",
Has this description been approved? I.e. is a starndard one we have?

2024-06-14 19:17 UTC, 552020 commented on manifest.json
For what is this manifest.json?

2024-06-14 19:17 UTC, 552020 commented on src/components/Word.tsx
> +      manifestUrl='https://yourappurl.com/tonconnect-manifest.json'
Here we need our app url, not 'yourappurl.com'!

2024-06-14 23:04 UTC, lmangall commented on manifest.json
> +	"description": "Earn money from your Telegram chats by bundling them into AI training datasets.",
It is

2024-06-14 23:05 UTC, lmangall commented on manifest.json
It's in their doc:
https://docs.ton.org/develop/dapps/ton-connect/web

Maybe we should open an issue to improve it in the future

2024-06-14 23:08 UTC, lmangall commented on src/components/Word.tsx
> +      manifestUrl='https://yourappurl.com/tonconnect-manifest.json'
We don't have a logo online, I just set the domain name to the vercel deployment, I guess as soon as we put a favicon for the website we can set the link here

2024-06-15 08:41 UTC, 552020 approved these changes
LGTM

2024-06-15 08:42 UTC, 552020 commented on src/components/Word.tsx
> +      manifestUrl='https://yourappurl.com/tonconnect-manifest.json'
This was about ot the logo online it was about having the our url there pointing to tonconnect-manifest.json

2024-06-15 13:26 UTC, merged