make app fullscreen
TON-42/new_vite_frontend pull request #17
Opened 2024-06-21 13:29 UTC by lmangall

Stefano's last PR documentation help me found something for this problem I tried to solve but couldn't.
Can only be tested in main...

2024-06-21 16:38 UTC, 552020 commented
But you know about this method right? @lmangall 

<img width="849" alt="image" src="https://github.com/TON-42/new_vite_frontend/assets/60273337/0a56669a-7c80-42ee-a04c-cb3b829f60c5">

Cause Gleb told about it during his lecture ...

2024-06-21 16:46 UTC, 552020 requested changes
I have some question and also the question if you know this method expand() ...

2024-06-21 16:46 UTC, 552020 commented on src/index.css
Here you are kind of adding CSS right, but we want to eliminate this sort of standard CSS and go Tailwind right?

2024-06-21 16:46 UTC, 552020 commented on src/App.tsx
As general question should the app always be full screen when launched or should the user have the possibility to have it fullscreeen or in the inside Telegram view. Tagging here also @Danielg1406, who maybe has more experience of TWA best UX practices.

2024-06-21 19:22 UTC, Danielg1406 commented on src/App.tsx
I think we should follow Gleb's advice to use expand because is more convenient for the user when opening our app. By default all apps only open partially so the user has to manually do it. In terms of UX is not ideal and I think if the expert is suggesting it, we should implement it
<img width="1440" alt="Screenshot 2024-06-21 at 9 20 47 PM" src="https://github.com/TON-42/new_vite_frontend/assets/105959136/bf2ddf96-c80c-4c73-bd91-882a479c9652">

2024-06-21 19:27 UTC, Danielg1406 requested changes
I agree with Stefano. I think it makes more sense to use the expand method rather than doing it with CSS

2024-06-22 16:09 UTC, lmangall commented
Stefano was for changing CSS to Tailwind wich I agree 100% with, but we need one of those.
JUst in case you haven't seen the issue @Danielg1406 I tried the code from Gleb's video but id didn't worked (back when we had a unprotected main)

2024-06-22 19:43 UTC, 552020 commented on src/App.tsx
If I understand the documentation(s) correctly window.Telegram.WebApp.expand() is from the Telegram SDK, and the  @tma.js SDK has this method: https://docs.telegram-mini-apps.com/platform/methods#web-app-expand. I watched the video now till to that point and he's not introduding the SDK, but for expand he's using the official SDK method but some second later for platform recognition he's using the @tma.js SDK method ...

2024-06-22 19:44 UTC, 552020 commented
> Stefano was for changing CSS to Tailwind wich I agree 100% with, but we need one of those. JUst in case you haven't seen the issue @Danielg1406 I tried the code from Gleb's video but id didn't worked (back when we had a unprotected main)

What do you mean @leo with "we need on of those"? 

And you tried to code from Gleb's video what exactly that didn't work?

2024-06-22 21:02 UTC, lmangall commented
> What do you mean @leo with "we need on of those"?

I was answering to Daniel's

> it makes more sense to use the expand method rather than doing it with CSS

meaning that we need a source of CSS in addition to expan

_______________________________________

> And you tried to code from Gleb's video what exactly that didn't work?
https://linear.app/chatpay/issue/CHA-365/open-the-mini-app-in-the-fullscreen-mode#comment-2942d70b

2024-07-03 18:58 UTC, 552020 commented
I'm closing this one. We need anyway to change SDK and use the methods from the new one (I guess). Even if it could be possible that Gleb is using both SDK at the same time. This is a good (and smart) question to ask to Gleb @lmangall I'll make an issue about it

2024-07-03 18:58 UTC, closed without merging