Danielgomeza1406/cha 450 store user state in db
TON-42/new_vite_frontend pull request #32
Opened 2024-06-27 08:57 UTC by Danielg1406

- Modify Login.tsx, types.d.ts, and utils.ts to adapt to the new auth_status.
- Modify multiple files to adapt to dark and light mode functionality as well as some components to have cohesion in the UI.

**P.S: Please check the auth_status implementation. I didn't have time to test it because that meant changing the mocks as well. @552020 @lmangall**

2024-06-27 09:28 UTC, lmangall commented on src/components/Chats.tsx
> +        style={{background: "var(--tgui--secondary_bg_color)"}}
That's CSS but I believe we cannot do it with tailwind so I think it's fine

2024-06-27 09:29 UTC, lmangall commented on src/components/Home.tsx
> -    <TonConnectUIProvider
why did you got rid of:
  ```
  <TonConnectUIProvider
      manifestUrl='https://yourappurl.com/tonconnect-manifest.json'
      actionsConfiguration={{
        twaReturnUrl: "https://t.me/chatpayapp_bot/chatpayapp",
      }}
```

2024-06-27 09:41 UTC, Danielg1406 commented on src/components/Home.tsx
> -    <TonConnectUIProvider
Because it does not work and that placement is weird, nobody notices it. So I kept the one at the Balance. Which also does not work out but I know how to fix it.

2024-06-27 09:46 UTC, lmangall commented on src/components/Login.tsx
> +  useEffect(() => {
I think this is not correct, you should use `import {useUserContext} from "../utils/utils";`
Because getUserDataFromTelegram does the API call to the backend and fill our context: useUserContext so we don't have to do further API calls (unless we need to update the context).

What should happen is that:
inside getUserDataFromBackend around line 51 we need to add a field for the new var `auth_status`

And in the same way upon opening of the app we  retrieve the data and fill the context in order to know if a user is a userB (Home.tsx line 20), we'll need to check if he started an "auth session".
But as I told you this (I think) is not a priority and might take some time to solve. We can start with the first step which is storing the auth_status in the context.

2024-06-27 09:47 UTC, Danielg1406 commented on src/components/Chats.tsx
> +        style={{background: "var(--tgui--secondary_bg_color)"}}
exactly I encountered the same problem as Stefano. It would not work with Tailwind. The components from the UI Kit are only changing its properties based on the inline style CSS

2024-06-27 09:48 UTC, lmangall commented on src/components/Modals/LastPerson.tsx
Why did you delete the file?

2024-06-27 09:49 UTC, lmangall commented on src/components/Modals/NotLastPerson.tsx
Same question: Why did you delete the file?

2024-06-27 09:50 UTC, Danielg1406 commented on src/components/Modals/LastPerson.tsx
because it was not necessary for the modal. I was not using it to confirm the last person because I created it directly from the ConfirmSale modal. I created that file in the first place but then noticed it was not necessary

2024-06-27 09:50 UTC, Danielg1406 commented on src/components/Modals/NotLastPerson.tsx
pretty much the same answer above

2024-06-27 09:51 UTC, lmangall commented on src/components/Word.tsx
Nice that you commented out the alert.
I think this is next important step to implement this tab (in another PR)

2024-06-27 09:52 UTC, lmangall commented on src/components/Home.tsx
We possibly have an autoformatter issue: when several team members have different autoformat settings, we get huge diffs for nothing, I'll create an issue as soon as my browser will accept opening Linear

2024-06-27 09:54 UTC, lmangall requested changes
One of my rare PR review in real @552020 style

2024-06-27 09:56 UTC, lmangall commented on src/components/Home.tsx
> -    <TonConnectUIProvider
Ok, if we have one then it's ok.

2024-06-27 10:10 UTC, lmangall commented on src/components/Modals/LastPerson.tsx
Ok, it seems to me (not 100%sure) that in ConfirmSale we have only the case for the last person, but not the "pending" case. If it is the case could you add a comment and create a linear issue if you don't want to implement it in this PR.

2024-06-27 10:54 UTC, Danielg1406 commented on src/components/Modals/LastPerson.tsx
yeah. We decided to do the day of the Pitch at 42 because we realized that we would receive a response from the backend with multiple chat statuses and IDs. The issue already exists its this one:

https://linear.app/chatpay/issue/CHA-390/solve-issue-http-request-response-userb

2024-06-27 13:05 UTC, 552020 commented on src/components/Home.tsx
I alreday setup the autoformatter for this project, actually.

2024-06-27 13:14 UTC, lmangall approved these changes
LGTM!

2024-06-27 13:18 UTC, merged

2024-06-27 14:01 UTC, 552020 reviewed
If I understand correctly what we are trying to do here, is to set an auth_status into the UserContext when the user try to Login. I.e. after the call to the send-code we should set this status and also tell the backend about this status. Actually I don't know why, cause the backend knows that if the user hit send-code, he wants to login. We also don't need to set this state, cause we will use this information only if the user is exiting the app before inserting the code, so the information will get lost. 

The backend should just keep some state of the User in the backend, and when the User  hit the send-code endpoint, it will set the status of the user to something like 'requestedCode'. This information will be sent when get-user is hit, so that if we get this status when the user enters the app we switch him directly to the screeen to enter the code. When login is hit this state in the backend is changed to the 'norma' state. 

It's not clear form the PR which are the auth_states that need to be communicated, and how we switch the user to the screen where he enters the code, when we get this status from the backend with get-user. 

I'm not sure if we need to keep an auth_state for the user or if only the backend should.

2024-06-28 06:08 UTC, lmangall commented
@552020 

> I'm not sure if we need to keep an auth_state for the user or if only the backend should.

We need to receive it so when the user opens the app we can know if we have to show the "enter code" component

I think @Danielg1406 also doesn't know what are the states of auth_status at the moment

2024-06-28 09:25 UTC, 552020 commented
> @552020
> 
> > I'm not sure if we need to keep an auth_state for the user or if only the backend should.
> 
> We need to receive it so when the user opens the app we can know if we have to show the "enter code" component
> 
> I think @Danielg1406 also doesn't know what are the states of auth_status at the moment

You didn't answer to my question @lmangall. I repeat: "I'm not sure if we need to keep an auth_state for the user or if only the backend should." Your answer was: we need to receive something. I was saying I don't know if we need to keep a state not I don't know if we need to receive something. (And I know what this thing is about, but thank for the explanation.)

2024-06-28 09:26 UTC, 552020 commented
> If I understand correctly what we are trying to do here, is to set an auth_status into the UserContext when the user try to Login. I.e. after the call to the send-code we should set this status and also tell the backend about this status. Actually I don't know why, cause the backend knows that if the user hit send-code, he wants to login. We also don't need to set this state, cause we will use this information only if the user is exiting the app before inserting the code, so the information will get lost.
> 
> The backend should just keep some state of the User in the backend, and when the User hit the send-code endpoint, it will set the status of the user to something like 'requestedCode'. This information will be sent when get-user is hit, so that if we get this status when the user enters the app we switch him directly to the screeen to enter the code. When login is hit this state in the backend is changed to the 'norma' state.
> 
> It's not clear form the PR which are the auth_states that need to be communicated, and how we switch the user to the screen where he enters the code, when we get this status from the backend with get-user.
> 
> I'm not sure if we need to keep an auth_state for the user or if only the backend should.

@Danielg1406