slombard/cha 464 solve different chips showing same chats
TON-42/new_vite_frontend pull request #38
Opened 2024-06-29 15:05 UTC by 552020

2024-06-30 12:43 UTC, Danielg1406 commented
I noticed it works pretty well for lead users. Now it only shows in the chats the one to sell and nothing in the part of the invitation. The only thing I noticed is that it shows immediately the chat tab and not the home tab. This could also just be a local behavior.

https://github.com/TON-42/new_vite_frontend/assets/105959136/99e56521-eae0-4c38-970e-5d2503602c19

2024-06-30 12:53 UTC, Danielg1406 commented
I noticed problems coming from the other users(invitee, new, regular(in the database this is saved as normal)). When I open the app after selecting those users in the .env it can't fetch the data. So it will not show their names and in the case of the invitee does not show anything in "My invitations".

<img width="1766" alt="Screenshot 2024-06-30 at 2 24 14 PM" src="https://github.com/TON-42/new_vite_frontend/assets/105959136/2d7874da-1603-4787-ba71-6b59d0229fcc">
<img width="1866" alt="Screenshot 2024-06-30 at 2 49 26 PM" src="https://github.com/TON-42/new_vite_frontend/assets/105959136/343ccebc-5a92-42da-b236-d83fc03e4948">

And the two chats to sell after logging in did show up but when I pressed to send the message it failed to make the request because of an incorrect body from the request

<img width="1690" alt="Screenshot 2024-06-30 at 2 29 15 PM" src="https://github.com/TON-42/new_vite_frontend/assets/105959136/37aa8051-6d3f-47d6-b50e-07804eafc4de">

Do you know why is working for the lead user but not for the other users?

2024-06-30 13:49 UTC, 552020 commented
> I noticed problems coming from the other users(invitee, new, regular(in the database this is saved as normal)). When I open the app after selecting those users in the .env it can't fetch the data. So it will not show their names and in the case of the invitee does not show anything in "My invitations".
> 
> 
> 
> <img width="1766" alt="Screenshot 2024-06-30 at 2 24 14 PM" src="https://github.com/TON-42/new_vite_frontend/assets/105959136/2d7874da-1603-4787-ba71-6b59d0229fcc">
> 
> <img width="1866" alt="Screenshot 2024-06-30 at 2 49 26 PM" src="https://github.com/TON-42/new_vite_frontend/assets/105959136/343ccebc-5a92-42da-b236-d83fc03e4948">
> 
> 
> 
> And the two chats to sell after logging in did show up but when I pressed to send the message it failed to make the request because of an incorrect body from the request
> 
> 
> 
> <img width="1690" alt="Screenshot 2024-06-30 at 2 29 15 PM" src="https://github.com/TON-42/new_vite_frontend/assets/105959136/37aa8051-6d3f-47d6-b50e-07804eafc4de">
> 
> 
> 
> Do you know why is working for the lead user but not for the other users?
> 
> 

I'm in Matseille outside and I can't check the laptop for the next hours. I guess the mocked chats are not passed to the User. It could also be that the other mocked Users beside the lead don't have chats. I'm not sure if it's clear what I mean. But thanks for checking it out!

2024-06-30 14:26 UTC, Danielg1406 commented
I just solved the issue with the other users. Mainly the problem comes from the getUserResolver.ts. I think there is something in the way you structured the user parameters because I pretty much kept them the same as they were before, just changed the status of the invitee chats to all of them to be pending and now it works as intended.


https://github.com/TON-42/new_vite_frontend/assets/105959136/fa080db5-8b85-41cd-bcba-4fc06a1dbe94

Here is the only thing I changed from the getUserResolver.ts
<img width="1440" alt="Screenshot 2024-06-30 at 4 19 47 PM" src="https://github.com/TON-42/new_vite_frontend/assets/105959136/d8987e21-eec4-4614-865d-984572fcc94b">
<img width="1440" alt="normal-user" src="https://github.com/TON-42/new_vite_frontend/assets/105959136/b70de404-0870-45cd-a0fa-56f9f0e3a951">


I don't know if this is the best way to implement it but it works now for all users and separates the chats for the invitee user

2024-06-30 14:31 UTC, Danielg1406 requested changes
Most of the implementation works perfectly The only problem is the getUserResolver.ts

2024-06-30 17:38 UTC, lmangall commented
Thanks guys for being on it
Regarding GitHub good practices @Danielg1406 if you solved a problem from this branch in one of your branch you should be able to open a PR to @552020 ‚s branch (this one, not main). I have never did it but it’s the way (I think) it is supposed to happen.

2024-06-30 17:40 UTC, Danielg1406 commented
Now, the only user that is causing problems is the "normal" user. I tested it locally and managed to interact with the backend. The problem is that is still sending an incorrect body request when selling a chat with someone.

<img width="1912" alt="Screenshot 2024-06-30 at 7 21 58 PM" src="https://github.com/TON-42/new_vite_frontend/assets/105959136/5372ff6e-0d6a-45f8-8e4c-a8be4fefaa39">


It also the same for the normal user
<img width="1903" alt="Screenshot 2024-06-30 at 7 39 40 PM" src="https://github.com/TON-42/new_vite_frontend/assets/105959136/2cb7e81c-1bfc-4e35-a68a-17568f93c120">


Aside from that the other two users (lead and invitee)work pretty well

2024-06-30 17:41 UTC, Danielg1406 commented
> Thanks guys for being on it Regarding GitHub good practices @Danielg1406 if you solved a problem from this branch in one of your branch you should be able to open a PR to @552020 ‚s branch (this one, not main). I have never did it but it’s the way (I think) it is supposed to happen.

I'll watch a video about that because I don't know how to do it

2024-06-30 22:02 UTC, 552020 commented
> > Thanks guys for being on it Regarding GitHub good practices @Danielg1406 if you solved a problem from this branch in one of your branch you should be able to open a PR to @552020 ‚s branch (this one, not main). I have never did it but it’s the way (I think) it is supposed to happen.
> 
> I'll watch a video about that because I don't know how to do it

Ok. This is goes this way:
- You checkout the branch you want to branch out from, in this case this branch: `git checkout slombard/cha-464-solve-different-chips-showing-same-chats`. 
- From that branch you create another branch `git checkout -b <your-branch-name>. You commit whatever you want, and then when you are done, you push to the remote. 
- You open a PR from GitHub from that branch into my branch: you do this operation from GitHub app. 
<img width="337" alt="image" src="https://github.com/TON-42/new_vite_frontend/assets/60273337/d3401d4f-fe04-4726-921c-24a614b12c73">
On the right side you select the branch you want to be merge into (normally) main. But you can change the branch on the fight side and select the branch you branched out from, which is this branch.

2024-06-30 22:06 UTC, 552020 commented
> Now, the only two users that are causing problems are the "normal" and "new" user. I tested it locally and managed to interact with the backend. The problem is that is still sending an incorrect body request when selling a chat with someone. New user:
> 
> <img alt="Screenshot 2024-06-30 at 7 21 58 PM" width="1912" src="https://private-user-images.githubusercontent.com/105959136/344483718-5372ff6e-0d6a-45f8-8e4c-a8be4fefaa39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3ODU0NTAsIm5iZiI6MTcxOTc4NTE1MCwicGF0aCI6Ii8xMDU5NTkxMzYvMzQ0NDgzNzE4LTUzNzJmZjZlLTBkNmEtNDVmOC04ZTRjLWE4YmU0ZmVmYWEzOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYzMFQyMjA1NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYzhkMjEyYmI0MjZjNGE1ZjU2NzA1YmRhYjVlNjk0MDE4NTI3NWIwNWYzNjljNTc5YTQwYTQ1NTQ3ZWZlNDUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cvU1WnFnyyeSt89AoVon8df_tIseIb56AZ-6mMK5f6o">
> It also the same for the normal user <img alt="Screenshot 2024-06-30 at 7 39 40 PM" width="1903" src="https://private-user-images.githubusercontent.com/105959136/344484225-2cb7e81c-1bfc-4e35-a68a-17568f93c120.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3ODU0NTAsIm5iZiI6MTcxOTc4NTE1MCwicGF0aCI6Ii8xMDU5NTkxMzYvMzQ0NDg0MjI1LTJjYjdlODFjLTFiZmMtNGUzNS1hNjhhLTE3NTY4ZjkzYzEyMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYzMFQyMjA1NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NzU4NjVhNjM3YmFlMTNhNWMwZWZjZmU4NjU1MGYzMzk3YWVmYWNjNmJkNzQ2ZjhjYjhiNWU3YTU4MWIwOTVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mZCAr-Xd4EGt-umjLuJPW7z12LELvJSR8attdFjiJrc">
> 
> Aside from that the other two users (lead and invitee)work pretty well

Thanks! Tomorrow I'll look into it ...

2024-07-01 05:14 UTC, 552020 commented
I approved your PR, kind of blindly ... ;-) @Danielg1406

2024-07-01 07:45 UTC, Danielg1406 approved these changes
great job!

2024-07-01 07:45 UTC, merged