Implement user leave app to check pin
TON-42/new_vite_frontend pull request #50
Opened 2024-07-02 19:19 UTC by lmangall

1. implement mocks for users with auth_status
Update .env with: `VITE_USER_TYPE=new  # Can be 'lead', 'invitee', 'new', 'new_auth_code', 'new_choose_chat'`

2024-07-02 20:41 UTC, lmangall commented
This isn't a lot of changes but was quite difficult to be honnest !

2024-07-02 20:48 UTC, 552020 requested changes

2024-07-02 20:48 UTC, 552020 commented on src/App.tsx
We don't want this. No? Pollute App.tsx with the Login component.

2024-07-02 21:03 UTC, 552020 commented on src/App.tsx
But Chat is like a Tab Component no? You should just control the flow to get there where the Login is displayed, not render it in another place. 

The onboard component are just modals on the top of Home no? so it's fine. 

> => I just realized we redirect UserB in both App.tsx and Home.tsx which might be a reason why we have redirect problems...

This is probably also not good.

2024-07-02 21:11 UTC, lmangall commented on src/App.tsx
> This is probably also not good.

Yes, next thing to solve
________________________________
> But Chat is like a Tab Component no?

Yes
________________________________

Okay, that makes a lot of sense, but how do you think about all these redirections to control the flow ? Is this good practice, is this the way we should do it ?

2024-07-02 21:15 UTC, 552020 commented on src/App.tsx
You want to bring the user back where they were, so you are on Home and from Home you render Login the enter phone or the enter code view depending on the status code, no?

"Redirections" are kind of conditional rendering depending on the state of the app, I guess it's the normal way of doing things.

2024-07-02 21:16 UTC, lmangall commented on src/App.tsx
Alright, will do, thanks for your help

2024-07-02 22:23 UTC, lmangall commented on src/App.tsx
Actually this doesn't make any difference for the user because the pin screen is fullscreen (native from Gleb's UI toolkit)

2024-07-03 05:40 UTC, 552020 commented
Is it ready, cause is still tagged as WIP? @lmangall

2024-07-03 10:55 UTC, 552020 approved these changes
LGTM

2024-07-03 10:55 UTC, merged