refactor(CustomError): move CustomError to types file
TON-42/new_vite_frontend pull request #63
Opened 2024-07-05 19:24 UTC by lmangall

- [x] move CustomError to types file
- [x] add error handling to get-user
- [x] add error handling to  add-user-to-agreed
- [ ] send-code
- [ ] login
- [ ] add error handling to  send-message

2024-07-06 09:39 UTC, 552020 commented
I'm checking this PR and trying to understand it. I started to check `/get-user`. You are not handling the error we get from the real API call (in utils.ts getUserDataFromBackend) but in the mocked function `getUserResolver`. If the env variable VITE_DEBUG_ENDPOINT  is set to "get-user", it will return a 500. @lmangall

2024-07-06 09:52 UTC, lmangall commented
@552020  You are right, I forgot to do it in utils.ts for get-user (I did it in ConfirmSale.tsx)
I added it now

2024-07-06 09:56 UTC, lmangall commented
>  If the env variable VITE_DEBUG_ENDPOINT is set to "get-user", it will return a 500

Yes this is expected


right now there is a problem with the get-user, the error is printed in console.log but not shown in the UI

2024-07-06 10:01 UTC, lmangall commented
It's done now, thanks for spotting the missing one

2024-07-06 10:16 UTC, 552020 commented
But /get-user can return: 400 (if the user is missing from the request), 404 (if the user is missing from the database) and 500. 
- 404 is the normal case for a new user or a browser user: so we should do nothing probably.
- 400 will probably never be the case, cause we send a default value. But we should catch the error anyway maybe.
- 500: how do you want to handle it? We are not able to retrieve the info of the user, and we tell the user what?

2024-07-06 10:18 UTC, 552020 requested changes

2024-07-06 10:18 UTC, 552020 commented on src/utils/utils.ts
> -    console.error("Error fetching user data:", error);
This is not good I think. 400 is the normal case for the new user.

2024-07-06 10:28 UTC, lmangall commented
> But /get-user can return: 400 (if the user is missing from the request), 404 (if the user is missing from the database) and 500.


Yes I know but I don't want to reimplement the whole backend to test each code, if one code works all the other should work. Eventually we can do it later, but now the goal is to have the minimal thing, that as instance would show to a user that we don't support 2FA.
The different actions to be taken depending on which error come from which endpoint will be handled in BackendError I think

2024-07-06 10:38 UTC, 552020 commented
> > But /get-user can return: 400 (if the user is missing from the request), 404 (if the user is missing from the database) and 500.
> 
> Yes I know but I don't want to reimplement the whole backend to test each code, if one code works all the other should work. Eventually we can do it later, but now the goal is to have the minimal thing, that as instance would show to a user that we don't support 2FA. The different actions to be taken depending on which error come from which endpoint will be handled in BackendError I think

What do you mean. I don't understand your message. Why should we reimplement the whole backend to test each code? These are the codes we get now. I was talk exclusively about /get-user now. 

If you need someone who just approve your request maybe you can ask @Danielg1406. He should be at school now.

2024-07-06 10:39 UTC, 552020 commented
The branch has also conflicts.

2024-07-06 10:52 UTC, lmangall commented
> What do you mean? I don't understand your message. Why should we reimplement the whole backend to test each code? These are the codes we get now. I was talk exclusively about /get-user in my message.

I thought you were talking about the mocks and meant that we have to enhance the mocks with more errors

Conflicts fixed


> If you need someone who just approve your request maybe you can ask @Danielg1406. He should be at school now.

Yes he is here, I appreciate your error checking and the fact that you found an API call unhandled !

2024-07-06 11:32 UTC, 552020 commented
<img width="1076" alt="image" src="https://github.com/TON-42/new_vite_frontend/assets/60273337/27b63fb5-6b93-400f-8640-2faf9574011e">

So you didn't change even this. @lmangall 

Happy you find someone who approve whatever you write! Great job! 👏

2024-07-06 12:23 UTC, lmangall commented
> So you didn't change even this. @lmangall


@552020  I asked you for clarification

<img width="847" alt="Screenshot 2024-07-06 at 14 22 57" src="https://github.com/TON-42/new_vite_frontend/assets/107299611/fa0b8338-d3fa-430a-8015-feee0e1678ce">

2024-07-06 12:50 UTC, 552020 commented
> > So you didn't change even this. @lmangall
> 
> @552020 I asked you for clarification
> 
> <img alt="Screenshot 2024-07-06 at 14 22 57" width="847" src="https://private-user-images.githubusercontent.com/107299611/346273336-fa0b8338-d3fa-430a-8015-feee0e1678ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyNzAzNjgsIm5iZiI6MTcyMDI3MDA2OCwicGF0aCI6Ii8xMDcyOTk2MTEvMzQ2MjczMzM2LWZhMGI4MzM4LWQzZmEtNDMwYS04MDE1LWZlZWUwZTE2NzhjZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNlQxMjQ3NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZDVmYThmMGVlNWFkYmI2MmVkYWYyZTMyNGI4ZTk3MjFiZWRmZTlmZjE3YTk1ZDUwZDJhMDQ5NDUxNmNhNWMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TLvw8mGo2WKXZdIwoAfhFPN6PT9yI7LxbysMz-k0_wk">

And you waited for the clarification I see. What there is to clarify? For a new user which is not in the db the backend will return a 400. You can just read which errors the backend returns (and in which cases) since you are implementing errors (or pretending to).

2024-07-07 00:04 UTC, 552020 requested changes
Please be more specific with the error

2024-07-07 00:04 UTC, 552020 commented on src/mocks/resolvers/sendMessageResolver.ts
> +      throw error;
error.status = import.meta.env.VITE_DEBUG_ENDPOINT_ERROR

2024-07-07 00:16 UTC, 552020 approved these changes
LGTM!

2024-07-07 00:16 UTC, merged