Add success modal  + login on home
TON-42/new_vite_frontend pull request #7
Opened 2024-06-14 11:16 UTC by lmangall

2024-06-14 12:23 UTC, 552020 requested changes

2024-06-14 12:23 UTC, 552020 commented on src/components/Chats.tsx
>      "https://daniilbot-k9qlu.ondigitalocean.app";
This should go as soon as possible.

2024-06-14 12:23 UTC, 552020 commented on src/components/Home.tsx
>            </div>
Since you are alrady touch this file, can you ask ChatGPT to convert the style={} stuff in tailwind.

2024-06-14 12:23 UTC, 552020 commented on src/components/Modals/AgreeSale.tsx
Is there a reason while we have all the Modals in 1 folder? They are not utilities components, like if you would write our own Modal to reuse in different component but are more subcomponent of other components, right?

2024-06-14 12:30 UTC, 552020 commented
The modal is there it's open. but the more important thing doesn't happen. The user should be switched to another tab/view.

2024-06-14 13:29 UTC, lmangall commented
> The modal is there it's open. but the more important thing doesn't happen. The user should be switched to another tab/view.


This is not critical in this PR I would say, it his critical for the UserB who open the app the first time (due to an invite)

Later we can switch the user to the "word" tab and show him his balance I guess

2024-06-15 08:40 UTC, 552020 approved these changes
LGTM

2024-06-15 13:41 UTC, merged